const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');

const postsDir = path.join(__dirname, '../src/posts');
const outputFile = path.join(__dirname, '../src/posts/posts.js');
const srcImagesDir = path.join(__dirname, '../src/assets/blog-images');
const publicImagesDir = path.join(__dirname, '../public/blog-images');

// Get all markdown files from posts directory (exclude README.md)
const files = fs.readdirSync(postsDir).filter(file => 
    file.endsWith('.md') && !file.toLowerCase().includes('readme')
);

const posts = [];

files.forEach(file => {
    const filePath = path.join(postsDir, file);
    const fileContent = fs.readFileSync(filePath, 'utf-8');
    const { data, content } = matter(fileContent);
    
    const slug = file.replace('.md', '');
    posts.push({
        slug,
        title: data.title || 'Untitled',
        date: data.date || new Date().toISOString(),
        description: data.description || '',
        ogImage: data.ogImage || null,
        content
    });
});

// Sort by date (newest first)
posts.sort((a, b) => new Date(b.date) - new Date(a.date));

// Generate the posts.js file
const output = `// This file is auto-generated by scripts/build-posts.js
// Do not edit manually

export const posts = ${JSON.stringify(posts, null, 2)};

export const getPostBySlug = (slug) => {
    return posts.find(post => post.slug === slug);
};

export const getAllPosts = () => {
    return posts;
};

export const getLatestPosts = (limit = 3) => {
    return posts.slice(0, limit);
};
`;

fs.writeFileSync(outputFile, output, 'utf-8');
console.log(`✓ Generated posts.js with ${posts.length} posts`);

// Copy blog images from src/assets/blog-images to public/blog-images
if (fs.existsSync(srcImagesDir)) {
    // Ensure public/blog-images directory exists
    if (!fs.existsSync(publicImagesDir)) {
        fs.mkdirSync(publicImagesDir, { recursive: true });
    }
    
    // Copy all image files
    const imageFiles = fs.readdirSync(srcImagesDir).filter(file => 
        /\.(jpg|jpeg|png|gif|webp|svg)$/i.test(file)
    );
    
    imageFiles.forEach(file => {
        const srcPath = path.join(srcImagesDir, file);
        const destPath = path.join(publicImagesDir, file);
        fs.copyFileSync(srcPath, destPath);
    });
    
    if (imageFiles.length > 0) {
        console.log(`✓ Copied ${imageFiles.length} image(s) to public/blog-images/`);
    }
}

